### ISSUE TITLE
GTK+ 3.18/20/22: indicator-applet-complete doesn't follow panel's bg color

### ISSUE THREAD

**Issue by monsta** [mate-desktop/mate-indicator-applet#17]
Originally reported at https://bugs.launchpad.net/bugs/1598159:

> If you change the color of the panel (in my case it's more Transparent) the Indicator Applet Complete 1.14.1 doesn't change the background color (will use the system theme)

Indeed, I can reproduce it in Ubuntu 16.10 which has GTK+3 build of MATE 1.14 now.
Here's how indicator-sound and indicator-messages look with transparent panel and TraditionalGreen theme:

![indicator-background](https://cloud.githubusercontent.com/assets/5138986/16682013/3526e18c-4509-11e6-9e57-2bb07b743019.png)

@raveit65 @lukefromdc @dnk @XRevan86
Guys, I need some help with this. I know that probably only @XRevan86 might be able to test this applet... but maybe you guys have some ideas that I could try.

So far, I've tried not to use some deprecated stuff in GTK+3 build (see https://github.com/mate-desktop/mate-indicator-applet/commit/0c50584e2b88f66874fff8587bcc0af1c9617ece). Also I've tried to use the applet as the second argument of `mate_panel_applet_set_background_widget` function (like it's done in all other applets):

``` diff
diff --git a/src/applet-main.c b/src/applet-main.c
index 1e00863..a274f64 100644
--- a/src/applet-main.c
+++ b/src/applet-main.c
@@ -1038,7 +1038,7 @@ applet_fill_cb (MatePanelApplet * applet, const gchar * iid G_GNUC_UNUSED,
                gtk_widget_show(item);
        } else {
                gtk_container_add(GTK_CONTAINER(applet), menubar);
-               mate_panel_applet_set_background_widget(applet, menubar);
+               mate_panel_applet_set_background_widget(applet, GTK_WIDGET(applet));
                gtk_widget_show(menubar);
        }
```

None of this helped. I still can't make it follow panel's bg color. :confused:

**Comment by monsta** [comment]
I also noticed that when no indicators are present, the label which tells us about it follows panel's bg color just fine. It can be reproduced by adding ```indicator-applet-appmenu``` applet to the panel while ```indicator-appmenu``` package isn't installed. It looks like this (see the leftmost applet):

![indicator-nothing-background](https://cloud.githubusercontent.com/assets/5138986/16682405/92da5028-450b-11e6-9805-7714814b1d65.png)

In the code the label is set as the bg widget, nothing special:

```C
	if (indicators_loaded == 0) {
		/* A label to allow for click through */
		GtkWidget * item = gtk_label_new(_("No Indicators"));
#if GTK_CHECK_VERSION(3, 0, 0)
		mate_panel_applet_set_background_widget(applet, item);
#endif
		gtk_container_add(GTK_CONTAINER(applet), item);
		gtk_widget_show(item);
	} else {
		gtk_container_add(GTK_CONTAINER(applet), menubar);
		mate_panel_applet_set_background_widget(applet, menubar);
		gtk_widget_show(menubar);
	}
```

So I don't get it why it works for a label but not for a menubar...

**Comment by lukefromdc** [comment]
I've not been able to make indicator-applet work at all on my Debian setup,
though the version tested was an old one. I had been wondering if it would
render indicator menus following the panel menu theme so as not to require
every tray applet that could be replaced by an indicator to support panel
menu themes.

**Comment by lukefromdc** [comment]
Which GTK 3 version is this?  There were radical changes in custom background code forced by the GTK 3.20 transition that were also applied to GTK 3.18 builds as they reduced the applet crash problem.  There were problems with backgrounds turning transparent which were a GtkPlug issue and required new code to put them in windows which then could be themed. This had to be used together with the code that moved the panel background handling to the toplevel to get consistant alpha values on transparent backgrounds.

If this applet and only this applet is mismatching custom panel backgrounds, it makes me wonder if it missed some code changes. Were any parts of the libmate-panel-applet code duplicated in this applet rather than dynamically linked perhaps?

As I said I've got now way to test this but I there is the possbility this is fallout from the panel background fixes forced by GTK 3.20. Current Ubuntu 16.04 LTS  uses 3.18-and so does the alpha Yakkety version. This means the new panel code would be used. If you were to build the panel and applet against an older version of Ubuntu and try again you could rule these code changes in or out. If the same issue comes up with GTK 3.16 or 3.14 the panel BG code changes are not the problem as they are only applied to GTK 3.18 or later builds. If this makes the differennce the panel BG code changes are the issue and some part of that didn't make it to this applet or is being improperly used. I haven't seen or heard of any other applet acting like this and tested a bunch of them while I was working on that panel code. Unfortunately indicator-applet doesn't work at all on my Debian setup as no indicators can be found even if installed.

**Comment by easdbe** [comment]
I thought I'd chime in regarding this bug. It doesn't only seem to affect indicator-applet, but (in my case at least) window buttons and the clock.

**Comment by lukefromdc** [comment]
Window buttons and clock have never acted like that on my systems.

**Comment by monsta** [comment]
This is with GTK+ 3.18 which is currently in Ubuntu 16.10. Only this applet behaves like that, and - see the code I quoted in my comment above - only when ```menubar``` widget is used. It's all good when a simple label is packed and displayed (see the screenshot in that comment as well).

That ```menubar``` widget is a GtkMenuBar in which some items are packed, it can be seen in ```entry_added``` function in ```src/applet-main.c```.

**Comment by monsta** [comment]
AFAIK, no parts of libmate-panel-applet code are duplicated here. It's all done like in all the other panel applets, we only call ```mate_panel_applet_set_background_widget``` function from the library, that's all.

**Comment by lukefromdc** [comment]
Looks like this problem was inherited from GNOME. From comments under
the original bug report https://bugs.launchpad.net/ubuntu-mate/+bug/1598159 

"Ok, so it's also broken in the original indicator-applet (for gnome-panel). 
That explains why it happens here even though I've adapted all their GTK+3 migration changes..."

**Comment by monsta** [comment]
Yes, that's my comment there :smile:

Indeed, the original indicator-applet running with gnome-panel 3.18 in gnome-flashback session (same system, Ubuntu 16.10) has the same issue.

@albertsmuktupavels: maybe you could give a hint about this please?

**Comment by albertsmuktupavels** [comment]
1) indicator-applet depends on ubuntu patches/changes in gtk+ that is not available in upstream gtk+. So that applet will not work in debian or other distributions unless they add needed patches.

2) I can make indicator-applet transparent by modifying Ambiance theme. At least Ambiance is setting background color and/or image on too many things. So probably first thing is to check themes?

**Comment by lukefromdc** [comment]
If the applet can be made transparent by modifying a theme, that means
it could be made theme-independent by hardcoding that same transparency
code into a cssprovider in the applet itself. I can't write that because I can't
test it though.  So long as you are getting the panel bg underneath and not
the desktop background (the old GtkPlug hole issue that could still affect 
GTK 3.16 and earlier builds) this should work.

**Comment by monsta** [comment]
Ok guys, you might be right about the themes...

A few days ago Ubuntu 16.10 finally got GTK+ 3.20, and suddenly, I have transparent background in the indicators. Even though I did **not** rebuild mate-panel and mate-indicator-applet (they're still built against GTK+ 3.18), it works. Not with all themes though.

It works with almost all themes from mate-themes package, except for two "Traditional" ones.
Also I've tested it with two themes that are shipped with Ubuntu MATE. With Radiant-MATE it works, with Ambiant-MATE it doesn't.

Radiant-MATE:
![mia-radiant](https://cloud.githubusercontent.com/assets/5138986/17772478/2b5b458c-655a-11e6-9845-be7651a7555d.png)

Menta:
![mia-menta](https://cloud.githubusercontent.com/assets/5138986/17772483/2f79b040-655a-11e6-814a-4ae32c8f4e6b.png)

Ambiant-MATE:
![mia-ambiant](https://cloud.githubusercontent.com/assets/5138986/17772488/34f1e2ae-655a-11e6-93d8-ab1429e02842.png)

TraditionalGreen:
![mia-tradgreen](https://cloud.githubusercontent.com/assets/5138986/17772492/3aac914e-655a-11e6-8917-f205c1f2ca3a.png)

**Comment by monsta** [comment]
Hmm... rebuilding both panel and indicator applet against 3.20 changed absolutely nothing. :confused:

**Comment by albertsmuktupavels** [comment]
Indicator applet use GtkMenuBar. Most likely both themes set background color on menubar.

https://code.launchpad.net/~albertsmuktupavels/ubuntu-themes/gnome-panel-3-20/+merge/302349
This is what I did for gnome-panel.

**Comment by monsta** [comment]
Themes issue for 3.20 is now tracked at https://github.com/flexiondotorg/ubuntu-mate-themes/issues/39. I'll leave this one open since we're going to stumble upon it in Mint 18.1 which has 3.18.9.

**Comment by raveit65** [comment]
```
/* mate-indicator-applet */
/* needed for a transparent panel */
#fast-user-switch-applet > #fast-user-switch-menubar {
    background-color: transparent;
}
```
Fixes the issue, or more general in gtk+-3.18 syntax.
.mate-panel-menu-bar .menubar {}
Honestly, using the style class '.menubar' is the real culprit, because this is set in every theme and complete useless here.
This is an applet with a menu but not a menubar ;)

**Comment by lukefromdc** [comment]
In my own theme, .mate-panel-menu-bar menubar{} (GTK3.20 syntax) is only used to deliberately override the use of  .mate-panel.menu.bar to set to overall panel background, so as not to also set it again on the main menubar or similar applets.

This sort of thing thus seems to come and go, at least GTK3 will now be stable and themes can thus also stabilize.  Although I can't test the indicator applet, to get all applets to respect panel transparency in my own theme required deliberate attention to detail, the old UbuntuStudio-Legacy GTK2 theme did NOT leave all applets properly showing the panel background.

If something causes problems in themes that do not refer to MATE at all, there is always the option of hardcoding it transparent as well.

**Comment by monsta** [comment]
Testing with 3.18... Weird. Mint-X doesn't have this issue even though there are no "fast-user-switch" things in css files. At the same time, all mate-themes have this issue...

**Comment by raveit65** [comment]
@monsta 
Does this help with our themes?
```
/* mate-indicator-applet */
/* needed for a transparent panel */
#fast-user-switch-applet > #fast-user-switch-menubar {
    background-color: transparent;
}
```
Add this to the end of mate-application.css.

**Comment by monsta** [comment]
Hmm I thought it was already committed... anyway, I added this to Menta and TraditionalGreen, and nothing changed.
I'm more curious about what in Mint-X could fix it.

**Comment by raveit65** [comment]
> I'm more curious about what in Mint-X could fix it.

Without looking into the code i would say they don't set 'menubar' in there css.
But i can reproduce this only with Trad themes in 17.14, we need to eliminate a background image too.
```
/* mate-indicator-applet */
/* needed for a transparent panel */
#fast-user-switch-applet > #fast-user-switch-menubar {
    background-color: transparent;
    background-image: none;
}
```
But why this applet draw his own background?
I should simply be transparent and use the bg from panel.

**Comment by monsta** [comment]
Yeah now it works :+1: 

Well, the code looks like it should use bg from panel (see code snippets in the first post above). Apparently something goes wrong there.

**Comment by raveit65** [comment]
I added this to all branches.
https://github.com/mate-desktop/mate-themes/commit/45f23d669a4706335060dc3b86913f6b414e7740

**Comment by sc0w** [comment]
there is a bounty here, currently 10$

https://www.bountysource.com/issues/35852416-gtk-3-18-20-22-indicator-applet-complete-doesn-t-follow-panel-s-bg-color

**Comment by raveit65** [comment]
@monsta 
Do you want to fix it in code?
Or should i claim the bounty as i fixed it in our and mate-ubuntu themes?

**Comment by lukefromdc** [comment]
If its fixed by theming rather than hardcoding the necessary elements, it's not fixed in non-MATE themes a user might install.

**Comment by monsta** [comment]
If the question is just bounty, you can claim it 😄 
I just would like to fix this in the code. Might be some hardcoding yes... or rather, some default setting that a theme could override.

**Comment by raveit65** [comment]
Well, the bounty is from mate-desktop itself, maybe someone like to remove the menubar style class from applet, this should fix the issue.

**Comment by lukefromdc** [comment]
The style class should stay on the menus popped up from the applet, or a mismatch will result in any theme that sets a mate-panel menu theme different from the overall GTK theme. Not a big deal to me as I use the tray's own SNI support rather than this applet. Speaking of that, what is in this applet that is not duplicated by the tray's native SNI support at this time?

**Comment by lukefromdc** [comment]
Clarification: the mate-panel-menu-bar style class needs to be on the menus popped up from the applet or on any parent widget to them, and when on an applet itself should make the applet look exactly the same as the main menu bar. That is, any lack of transparency on this applet that is not also a problem on the main menu bar has more to it. Use of the overall style class menubar rather than mate-panel-menu-bar , on the other hand, could cause exactly this problem and would NOT fix such a menu mismatch.

Having never worked on this applet (could not make it work when I tried, not on ubuntu), I have never worked on it so I would not have applied mate-panel-menu-bar to get menus to match those created by the main menu bar when the theme sets
```
 .mate-panel-menu-bar menu{
}
```

**Comment by monsta** [comment]
> Speaking of that, what is in this applet that is not duplicated by the tray's native SNI support at this time?

This applet is just a container for indicator-application, indicator-sound and other kinds of indicators. Only indicator-application has functionality available in tray's SNI support.

**Comment by monsta** [comment]
What can be removed from the code? The only style-related thing I found is:
```
gtk_widget_set_name(GTK_WIDGET (menubar), "fast-user-switch-menubar");
```
But removing it doesn't fix the issue. It only makes the issue appear for the themes where it was fixed previously (e.g. TraditionalGreen).

**Comment by lukefromdc** [comment]
OK, this looks like the fix is to either apply .mate-panel-menu-bar to the applet so it will always match the styling of the main menu bar (which is normally transparent), or to hardcode the background transparent. The former is probably the way to go as it also ensure consistant menus, but I cannot test this as I am not on Ubuntu and my last attempt to build and run this failed. Otherwise I would take care of this myself.

**Comment by monsta** [comment]
I also wonder why `mate_panel_applet_set_background_widget` works for a label but not for the actual indicator, as I mentioned in https://github.com/mate-desktop/mate-indicator-applet/issues/17#issuecomment-231310530 above.

**Comment by monsta** [comment]
@lukefromdc: I've adapted indicator-application for Debian, it's in [my repo](https://github.com/monsta/indicator-application).

It includes `debian` folder, so you can build .deb with `dpkg-buildpackage` tool.

I've enabled autostarting in MATE so that it would automatically load into mate-indicator-applet. You can disable it the usual way, via mate-session-properties.

To make the applet actually show something, just run some app with appindicator support. To avoid any conflicts, it's better to disable tray's SNI support first.

**Comment by lukefromdc** [comment]
I was able to build and install mate-indicator-applet, and (from https://github.com/monsta/indicator-application ) indicator-application and with some fiddleing get my indicators into them. I found that I was unable to duplicate the non-transparent background issue however, in any theme including Adwaita. It just plain worked fine.  I've got GTK 3.22.26 and mate-panel from current git master, if that's any indicator so to speak.

**Comment by monsta** [comment]
Remove this part from `mate-applications.css`:

```css
/* mate-indicator-applet */
/* needed for a transparent panel */
#fast-user-switch-applet > #fast-user-switch-menubar {
    background-color: transparent;
    background-image: none;
}
```

However, I don't know why the problem isn't reproducible with Adwaita, while it doesn't have any specific theming for this applet. 😕

**Comment by lukefromdc** [comment]
I don't have that in my theme either and didn't see the problem there

**Comment by monsta** [comment]
I've tested this modification with TraditionalGreen theme.

**Comment by raveit65** [comment]
I assume that the fix in themes is enough as nobody try to add a general fix in code.
Feel free to re-open it if you don't agree.

**Comment by simurgh9** [comment]
I just had this issue and it was very frustrating to figure out where to even put that CSS. Someone should definitely add the general fix. BTW the CSS bellow goes here `~/.config/gtk-3.0/gtk.css`.

```css
/* mate-indicator-applet */
/* needed for a transparent panel */
#fast-user-switch-applet > #fast-user-switch-menubar {
    background-color: transparent;
    background-image: none;
}
```

**Comment by RayneYoruka** [comment]
I'm surprised that, to this day this fix from above is working and that it isn't implemented.
